version: "3.8"                                  # docker-compose 파일 버전입니다.
services:                                       # 이 항목 밑에 실행하려는 컨테이너들을 정의
  community-redis-local:                        # 서비스명을 선언합니다.
    container_name: community-redis-local       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: kmnine3/community-redis-local        # 도커 허브 아이디 / 도커 이미지 이름
    ports:
      - "6379:6379"
  community-database-local:
    container_name: community-database-local
    build:
      dockerfile: Dockerfile
      context: ./database
    image: kmnine3/community-database-local     # 도커 허브 아이디 / 도커 이미지 이름
    environment:                                # 환경 변수
      - MYSQL_DATABASE=community
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:                                    # {호스트}:{컨테이너}
      - ./database/conf.d:/etc/mysql/conf.d
    ports:
      - "13306:3306"