spring:
  profiles:
    default: local
  config:
    import:
      - classpath:application-core.yml
      - classpath:application-secret.properties

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod