spring:
  profiles:
    default: local
  # Spring Security 의존성을 추가하면 기본적으로 로그인 가능한 id / password를 제공해주는데
  # 해당 계정을 직접 설정하여 콘솔에 노출안되게 처리
  security:
    user:
      name: ENC(ja4wqYSLV5gXdvHNXoW1ZQ==)
      password: ENC(daqoR41Dk9KfQzsF74LilJ7we0coCPQMVTUiJn9K2jg=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

---
spring:
  config:
    activate:
      on-profile: local
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:13306/community
    username: ENC(Pz95pAXc82ztjV2nYizKcw==)
    password: ENC(DXUafY6Wwez8jqvGrq6/9LqTw0gjtDjC)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # `create` or `none`
    properties:
      hibernate:
        show_sql: true # to System OutDataSourceConfiguration
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul # @CreatedDate 필드의 Time Zone 값 설정
  redis:
    host: localhost
    port: 6379

jwt:
  token:
    access:
      secret-key: ENC(ndzgfjpjB0v3t01nqGLS1hYk3AJwaX3B0LSY0ojq3SphRUeurBqSzomPBDVB1sbtLzAW3+5LZ9vu0nsCcHEpBQ==)
      # 30 min
      expired-time-ms: 1800000
    refresh:
      secret-key: ENC(ndzgfjpjB0v3t01nqGLS1hYk3AJwaX3B0LSY0ojq3SphRUeurBqSzomPBDVB1sbtLzAW3+5LZ9vu0nsCcHEpBQ==)
      # 7 day
      expired-time-ms: 604800000

---
spring:
  config:
    activate:
      on-profile: prod
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://communitydb-1.cbsohlk1oc4x.ap-northeast-2.rds.amazonaws.com:3306/community
    username: ENC(jT23So4awUThKjJQt0YQYw==)
    password: ENC(t3a9sHvfFD8s27ubDH1juaTCN6kupZGZ)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none # `create` or `none`
    properties:
      hibernate:
        show_sql: true # to System OutDataSourceConfiguration
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul # @CreatedDate 필드의 Time Zone 값 설정
  redis:
    host: community-redis
    port: 6379

jwt:
  token:
    access:
      secret-key: ENC(ndzgfjpjB0v3t01nqGLS1hYk3AJwaX3B0LSY0ojq3SphRUeurBqSzomPBDVB1sbtLzAW3+5LZ9vu0nsCcHEpBQ==)
      # 30 min
      expired-time-ms: 1800000
    refresh:
      secret-key: ENC(ndzgfjpjB0v3t01nqGLS1hYk3AJwaX3B0LSY0ojq3SphRUeurBqSzomPBDVB1sbtLzAW3+5LZ9vu0nsCcHEpBQ==)
      # 7 day
      expired-time-ms: 604800000