spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:13306/community
    username: ENC(Pz95pAXc82ztjV2nYizKcw==)
    password: ENC(DXUafY6Wwez8jqvGrq6/9LqTw0gjtDjC)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # `create` or `none`
    properties:
      hibernate:
        show_sql: true # to System OutDataSourceConfiguration
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul # @CreatedDate 필드의 Time Zone 값 설정

jwt:
  secret-key: ENC(ndzgfjpjB0v3t01nqGLS1hYk3AJwaX3B0LSY0ojq3SphRUeurBqSzomPBDVB1sbtLzAW3+5LZ9vu0nsCcHEpBQ==)
  token:
    expired-time-ms: 2592000000 # 30days

---
spring:
  config:
    activate:
      on-profile: prod
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: ENC(Pz95pAXc82ztjV2nYizKcw==)
    password: ENC(DXUafY6Wwez8jqvGrq6/9LqTw0gjtDjC)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none # `create` or `none`
    properties:
      hibernate:
        show_sql: true # to System OutDataSourceConfiguration
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul # @CreatedDate 필드의 Time Zone 값 설정

jwt:
  secret-key: ENC(ndzgfjpjB0v3t01nqGLS1hYk3AJwaX3B0LSY0ojq3SphRUeurBqSzomPBDVB1sbtLzAW3+5LZ9vu0nsCcHEpBQ==)
  token:
    expired-time-ms: 2592000000 # 30days